window.ROZVRH_DATA = {
  updated: "2026-09-07",
  days: ["Pondelok", "Utorok", "Streda", "Štvrtok", "Piatok"],
  slots: [
    "07:15–08:45",
    "09:00–10:30",
    "10:45–12:15",
    "12:30–14:00",
    "14:15–15:45",
    "16:00–17:30",
    "17:45–19:15"
  ],
  subjects: [
    {
      id: "digital",
      code: "440210401",
      short: "Digitálne systémy",
      name: "Základy digitálních systémů",
      requirement: "P+C",
      color: "#60a5fa",
      sessions: [
        { id: "digital-p02", type: "P", group: "P/02", day: 0, slot: 2 },
        { id: "digital-p01", type: "P", group: "P/01", day: 3, slot: 0 },
        { id: "digital-c18", type: "C", group: "C/18", day: 0, slot: 0 },
        { id: "digital-c14", type: "C", group: "C/14", day: 0, slot: 1 },
        { id: "digital-c01", type: "C", group: "C/01", day: 0, slot: 2 },
        { id: "digital-c16", type: "C", group: "C/16", day: 0, slot: 3 },
        { id: "digital-c02", type: "C", group: "C/02", day: 0, slot: 4 },
        { id: "digital-c17", type: "C", group: "C/17", day: 0, slot: 5 },
        { id: "digital-c21", type: "C", group: "C/21", day: 0, slot: 6 },
        { id: "digital-c03", type: "C", group: "C/03", day: 1, slot: 0 },
        { id: "digital-c09", type: "C", group: "C/09", day: 1, slot: 5 },
        { id: "digital-c22", type: "C", group: "C/22", day: 1, slot: 6 },
        { id: "digital-c04", type: "C", group: "C/04", day: 2, slot: 0 },
        { id: "digital-c07", type: "C", group: "C/07", day: 2, slot: 1 },
        { id: "digital-c06", type: "C", group: "C/06", day: 2, slot: 2 },
        { id: "digital-c05", type: "C", group: "C/05", day: 2, slot: 3 },
        { id: "digital-c08", type: "C", group: "C/08", day: 2, slot: 4 },
        { id: "digital-c15", type: "C", group: "C/15", day: 2, slot: 5 },
        { id: "digital-c23", type: "C", group: "C/23", day: 2, slot: 6 },
        { id: "digital-c19", type: "C", group: "C/19", day: 3, slot: 0 },
        { id: "digital-c10", type: "C", group: "C/10", day: 3, slot: 1 },
        { id: "digital-c11", type: "C", group: "C/11", day: 3, slot: 2 },
        { id: "digital-c12", type: "C", group: "C/12", day: 3, slot: 4 },
        { id: "digital-c13", type: "C", group: "C/13", day: 3, slot: 5 },
        { id: "digital-c24", type: "C", group: "C/24", day: 3, slot: 6 }
      ]
    },
    {
      id: "logic",
      code: "460205103",
      short: "Logické myslenie",
      name: "Úvod do logického myšlení",
      requirement: "P+C",
      color: "#a78bfa",
      sessions: [
        { id: "logic-p01", type: "P", group: "P/01", day: 0, slot: 0 },
        { id: "logic-c05", type: "C", group: "C/05", day: 0, slot: 1 },
        { id: "logic-c20", type: "C", group: "C/20", day: 0, slot: 4 },
        { id: "logic-c06", type: "C", group: "C/06", day: 0, slot: 4 },
        { id: "logic-c11", type: "C", group: "C/11", day: 1, slot: 0 },
        { id: "logic-c07", type: "C", group: "C/07", day: 1, slot: 0 },
        { id: "logic-c12", type: "C", group: "C/12", day: 1, slot: 2 },
        { id: "logic-c08", type: "C", group: "C/08", day: 1, slot: 2 },
        { id: "logic-c13", type: "C", group: "C/13", day: 1, slot: 3 },
        { id: "logic-c09", type: "C", group: "C/09", day: 1, slot: 3 },
        { id: "logic-c03", type: "C", group: "C/03", day: 1, slot: 3 },
        { id: "logic-c04", type: "C", group: "C/04", day: 1, slot: 4 },
        { id: "logic-c14", type: "C", group: "C/14", day: 2, slot: 2 },
        { id: "logic-c10", type: "C", group: "C/10", day: 2, slot: 2 },
        { id: "logic-c15", type: "C", group: "C/15", day: 2, slot: 3 },
        { id: "logic-c16", type: "C", group: "C/16", day: 2, slot: 4 },
        { id: "logic-c01", type: "C", group: "C/01", day: 3, slot: 1 },
        { id: "logic-c02", type: "C", group: "C/02", day: 3, slot: 2 },
        { id: "logic-c19", type: "C", group: "C/19", day: 3, slot: 4 }
      ]
    },
    {
      id: "programming",
      code: "460205205",
      short: "Programovanie",
      name: "Úvod do programování",
      requirement: "P+C",
      color: "#f59e0b",
      sessions: [
        { id: "programming-p01", type: "P", group: "P/01", day: 1, slot: 1, week: "sudý týždeň" },
        { id: "programming-p02", type: "P", group: "P/02", day: 1, slot: 1, week: "lichý týždeň" },
        { id: "programming-c05", type: "C", group: "C/05", day: 0, slot: 1 },
        { id: "programming-c01", type: "C", group: "C/01", day: 0, slot: 1 },
        { id: "programming-c15", type: "C", group: "C/15", day: 0, slot: 2 },
        { id: "programming-c02", type: "C", group: "C/02", day: 0, slot: 2 },
        { id: "programming-c16", type: "C", group: "C/16", day: 0, slot: 4 },
        { id: "programming-c17", type: "C", group: "C/17", day: 0, slot: 5 },
        { id: "programming-c22", type: "C", group: "C/22", day: 0, slot: 5 },
        { id: "programming-c20", type: "C", group: "C/20", day: 1, slot: 2 },
        { id: "programming-c06", type: "C", group: "C/06", day: 1, slot: 2 },
        { id: "programming-c21", type: "C", group: "C/21", day: 1, slot: 3 },
        { id: "programming-c07", type: "C", group: "C/07", day: 1, slot: 3 },
        { id: "programming-c08", type: "C", group: "C/08", day: 1, slot: 4 },
        { id: "programming-c03", type: "C", group: "C/03", day: 1, slot: 6 },
        { id: "programming-c18", type: "C", group: "C/18", day: 2, slot: 4 },
        { id: "programming-c04", type: "C", group: "C/04", day: 2, slot: 4 },
        { id: "programming-c19", type: "C", group: "C/19", day: 2, slot: 5 },
        { id: "programming-c12", type: "C", group: "C/12", day: 3, slot: 0 },
        { id: "programming-c13", type: "C", group: "C/13", day: 3, slot: 1 },
        { id: "programming-c14", type: "C", group: "C/14", day: 3, slot: 2 },
        { id: "programming-c09", type: "C", group: "C/09", day: 3, slot: 4 },
        { id: "programming-c10", type: "C", group: "C/10", day: 3, slot: 5 },
        { id: "programming-c11", type: "C", group: "C/11", day: 3, slot: 6 }
      ]
    },
    {
      id: "it",
      code: "460207901",
      short: "ZIT",
      name: "Základy informačních technologií",
      requirement: "P+C",
      color: "#22c55e",
      missingLecture: true,
      sessions: [
        { id: "it-c02", type: "C", group: "C/02", day: 1, slot: 3 },
        { id: "it-c03", type: "C", group: "C/03", day: 1, slot: 4 },
        { id: "it-c01", type: "C", group: "C/01", day: 2, slot: 1 },
        { id: "it-c04", type: "C", group: "C/04", day: 2, slot: 2 }
      ]
    },
    {
      id: "algebra",
      code: "470220501",
      short: "Lineárna algebra",
      name: "Lineární algebra",
      requirement: "P+C",
      color: "#f97316",
      sessions: [
        { id: "algebra-p01", type: "P", group: "P/01", day: 0, slot: 3 },
        { id: "algebra-c04", type: "C", group: "C/04", day: 0, slot: 4 },
        { id: "algebra-c05", type: "C", group: "C/05", day: 0, slot: 5 },
        { id: "algebra-c01", type: "C", group: "C/01", day: 0, slot: 5 },
        { id: "algebra-c02", type: "C", group: "C/02", day: 3, slot: 1 },
        { id: "algebra-c06", type: "C", group: "C/06", day: 3, slot: 2 },
        { id: "algebra-c07", type: "C", group: "C/07", day: 3, slot: 4 },
        { id: "algebra-c03", type: "C", group: "C/03", day: 3, slot: 5 }
      ]
    },
    {
      id: "law",
      code: "711043901",
      short: "Právo v ICT",
      name: "Právo v ICT",
      requirement: "C",
      color: "#ec4899",
      sessions: [
        { id: "law-c04", type: "C", group: "C/04", day: 0, slot: 4 },
        { id: "law-c16", type: "C", group: "C/16", day: 0, slot: 5 },
        { id: "law-c15", type: "C", group: "C/15", day: 0, slot: 6 },
        { id: "law-c03", type: "C", group: "C/03", day: 1, slot: 2 },
        { id: "law-c06", type: "C", group: "C/06", day: 2, slot: 1 },
        { id: "law-c07", type: "C", group: "C/07", day: 2, slot: 2 },
        { id: "law-c08", type: "C", group: "C/08", day: 2, slot: 3 },
        { id: "law-c11", type: "C", group: "C/11", day: 2, slot: 4 },
        { id: "law-c14", type: "C", group: "C/14", day: 3, slot: 3 },
        { id: "law-c12", type: "C", group: "C/12", day: 3, slot: 4 },
        { id: "law-c10", type: "C", group: "C/10", day: 3, slot: 5 },
        { id: "law-c09", type: "C", group: "C/09", day: 3, slot: 6 }
      ]
    },
    {
      id: "english",
      code: "712012401",
      short: "Angličtina",
      name: "Jazyk anglický I pro FEI - pokročilá úroveň",
      requirement: "C",
      color: "#14b8a6",
      sessions: [
        { id: "english-c07", type: "C", group: "C/07", day: 0, slot: 1, teacher: "Landry M.", room: "PORKA230" },
        { id: "english-c03", type: "C", group: "C/03", day: 0, slot: 1, teacher: "Pastorková K.", room: "PORJB240" },
        { id: "english-c01", type: "C", group: "C/01", day: 0, slot: 1, teacher: "Illík P.", room: "PORD105" },
        { id: "english-c11", type: "C", group: "C/11", day: 0, slot: 2, teacher: "Smutná K.", room: "PORK308" },
        { id: "english-c04", type: "C", group: "C/04", day: 0, slot: 2, teacher: "Pastorková K.", room: "PORJB240" },
        { id: "english-c02", type: "C", group: "C/02", day: 0, slot: 2, teacher: "Illík P.", room: "PORD105" },
        { id: "english-c18", type: "C", group: "C/18", day: 0, slot: 3, teacher: "Pachula J.", room: "PORB6" },
        { id: "english-c05", type: "C", group: "C/05", day: 0, slot: 3, teacher: "Pastorková K.", room: "PORJB240" },
        { id: "english-c21", type: "C", group: "C/21", day: 0, slot: 4, teacher: "Spurná K.", room: "PORJD358" },
        { id: "english-c17", type: "C", group: "C/17", day: 0, slot: 4, teacher: "Adámková J.", room: "PORD121" },
        { id: "english-c08", type: "C", group: "C/08", day: 0, slot: 4, teacher: "Šnicer M.", room: "PORKA215" },
        { id: "english-c09", type: "C", group: "C/09", day: 0, slot: 4, teacher: "Košťál M.", room: "PORKA204" },
        { id: "english-c12", type: "C", group: "C/12", day: 0, slot: 4, teacher: "Smutná K.", room: "PORK308" },
        { id: "english-c13", type: "C", group: "C/13", day: 0, slot: 5, teacher: "Košťál M.", room: "PORKA204" },
        { id: "english-c06", type: "C", group: "C/06", day: 0, slot: 5, teacher: "Pachula J.", room: "PORJD361" },
        { id: "english-c14", type: "C", group: "C/14", day: 1, slot: 2, teacher: "Spurná K.", room: "PORD109" },
        { id: "english-c15", type: "C", group: "C/15", day: 2, slot: 3, teacher: "Zouhar T.", room: "PORJD361" },
        { id: "english-c22", type: "C", group: "C/22", day: 2, slot: 4, teacher: "Landry M.", room: "PORJB240" },
        { id: "english-c20", type: "C", group: "C/20", day: 2, slot: 4, teacher: "Košťál M.", room: "PORRV202" },
        { id: "english-c19", type: "C", group: "C/19", day: 2, slot: 5, teacher: "Matyášková G.", room: "PORKA227" },
        { id: "english-c10", type: "C", group: "C/10", day: 3, slot: 2, teacher: "Landry M.", room: "PORD121" },
        { id: "english-c16", type: "C", group: "C/16", day: 4, slot: 2, teacher: "Chudašová G.", room: "PORJD358" }
      ]
    }
  ],
  templates: [
    {
      id: "a-compact",
      name: "A — Po–St, minimum dier",
      description: "Pôvodný favorit: súvislé bloky, štvrtok a piatok voľné.",
      sessionIds: [
        "logic-p01",
        "english-c07",
        "digital-p02",
        "algebra-p01",
        "algebra-c04",
        "programming-p01",
        "logic-c12",
        "it-c02",
        "programming-c08",
        "law-c06",
        "digital-c06"
      ],
      warnings: ["Chýba termín prednášky zo Základov informačních technologií, preto šablóna zatiaľ nie je úplná."]
    },
    {
      id: "a-english-wed",
      name: "A2 — Angličtina v stredu",
      description: "Ačko bez pondelkovej angličtiny; angličtina je v stredu po digitálnych systémoch.",
      sessionIds: [
        "logic-p01",
        "digital-p02",
        "algebra-p01",
        "algebra-c04",
        "programming-p01",
        "logic-c12",
        "it-c02",
        "programming-c08",
        "law-c06",
        "digital-c06",
        "english-c15"
      ],
      warnings: ["Chýba termín prednášky zo Základov informačních technologií, preto šablóna zatiaľ nie je úplná."]
    }
  ]
};